<?php

namespace Container3PrVoUu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XH6OEtYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XH6OEtY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XH6OEtY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityCategoryController::abilityCategoryCreate()', 'getAbilityCategoryControllerabilityCategoryCreateService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryEdit' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryEdit()', 'getAbilityCategoryControllerabilityCategoryEditService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryDelete' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryDelete()', 'getAbilityCategoryControllerabilityCategoryDeleteService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryList' => ['privates', '.service_locator.bVsO2JX.App\\Controller\\AbilityCategoryController::abilityCategoryList()', 'getAbilityCategoryControllerabilityCategoryListService', true],
            'App\\Controller\\AbilityController::abilityCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityController::abilityCreate()', 'getAbilityControllerabilityCreateService', true],
            'App\\Controller\\AbilityController::abilityEdit' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityEdit()', 'getAbilityControllerabilityEditService', true],
            'App\\Controller\\AbilityController::abilityDelete' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityDelete()', 'getAbilityControllerabilityDeleteService', true],
            'App\\Controller\\AbilityController::abilityList' => ['privates', '.service_locator.imJR4sZ.App\\Controller\\AbilityController::abilityList()', 'getAbilityControllerabilityListService', true],
            'App\\Controller\\CardController::list' => ['privates', '.service_locator.NMBx11d.App\\Controller\\CardController::list()', 'getCardControllerlistService', true],
            'App\\Controller\\CardController::cardCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\CardController::cardCreate()', 'getCardControllercardCreateService', true],
            'App\\Controller\\CardController::cardEdit' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardEdit()', 'getCardControllercardEditService', true],
            'App\\Controller\\CardController::cardDelete' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardDelete()', 'getCardControllercardDeleteService', true],
            'App\\Controller\\CardController::cardList' => ['privates', '.service_locator.NMBx11d.App\\Controller\\CardController::cardList()', 'getCardControllercardListService', true],
            'App\\Controller\\SecurityController::signIn' => ['privates', '.service_locator.UmW841m.App\\Controller\\SecurityController::signIn()', 'getSecurityControllersignInService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::userCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\UserController::userCreate()', 'getUserControlleruserCreateService', true],
            'App\\Controller\\UserController::userEdit' => ['privates', '.service_locator.6uK6gmq.App\\Controller\\UserController::userEdit()', 'getUserControlleruserEditService', true],
            'App\\Controller\\UserController::userDelete' => ['privates', '.service_locator.6uK6gmq.App\\Controller\\UserController::userDelete()', 'getUserControlleruserDeleteService', true],
            'App\\Controller\\UserController::userList' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::userList()', 'getUserControlleruserListService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityCategoryController::abilityCategoryCreate()', 'getAbilityCategoryControllerabilityCategoryCreateService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryEdit' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryEdit()', 'getAbilityCategoryControllerabilityCategoryEditService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryDelete' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryDelete()', 'getAbilityCategoryControllerabilityCategoryDeleteService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryList' => ['privates', '.service_locator.bVsO2JX.App\\Controller\\AbilityCategoryController::abilityCategoryList()', 'getAbilityCategoryControllerabilityCategoryListService', true],
            'App\\Controller\\AbilityController:abilityCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityController::abilityCreate()', 'getAbilityControllerabilityCreateService', true],
            'App\\Controller\\AbilityController:abilityEdit' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityEdit()', 'getAbilityControllerabilityEditService', true],
            'App\\Controller\\AbilityController:abilityDelete' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityDelete()', 'getAbilityControllerabilityDeleteService', true],
            'App\\Controller\\AbilityController:abilityList' => ['privates', '.service_locator.imJR4sZ.App\\Controller\\AbilityController::abilityList()', 'getAbilityControllerabilityListService', true],
            'App\\Controller\\CardController:list' => ['privates', '.service_locator.NMBx11d.App\\Controller\\CardController::list()', 'getCardControllerlistService', true],
            'App\\Controller\\CardController:cardCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\CardController::cardCreate()', 'getCardControllercardCreateService', true],
            'App\\Controller\\CardController:cardEdit' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardEdit()', 'getCardControllercardEditService', true],
            'App\\Controller\\CardController:cardDelete' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardDelete()', 'getCardControllercardDeleteService', true],
            'App\\Controller\\CardController:cardList' => ['privates', '.service_locator.NMBx11d.App\\Controller\\CardController::cardList()', 'getCardControllercardListService', true],
            'App\\Controller\\SecurityController:signIn' => ['privates', '.service_locator.UmW841m.App\\Controller\\SecurityController::signIn()', 'getSecurityControllersignInService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:userCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\UserController::userCreate()', 'getUserControlleruserCreateService', true],
            'App\\Controller\\UserController:userEdit' => ['privates', '.service_locator.6uK6gmq.App\\Controller\\UserController::userEdit()', 'getUserControlleruserEditService', true],
            'App\\Controller\\UserController:userDelete' => ['privates', '.service_locator.6uK6gmq.App\\Controller\\UserController::userDelete()', 'getUserControlleruserDeleteService', true],
            'App\\Controller\\UserController:userList' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::userList()', 'getUserControlleruserListService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryCreate' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryEdit' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryDelete' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryList' => '?',
            'App\\Controller\\AbilityController::abilityCreate' => '?',
            'App\\Controller\\AbilityController::abilityEdit' => '?',
            'App\\Controller\\AbilityController::abilityDelete' => '?',
            'App\\Controller\\AbilityController::abilityList' => '?',
            'App\\Controller\\CardController::list' => '?',
            'App\\Controller\\CardController::cardCreate' => '?',
            'App\\Controller\\CardController::cardEdit' => '?',
            'App\\Controller\\CardController::cardDelete' => '?',
            'App\\Controller\\CardController::cardList' => '?',
            'App\\Controller\\SecurityController::signIn' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::userCreate' => '?',
            'App\\Controller\\UserController::userEdit' => '?',
            'App\\Controller\\UserController::userDelete' => '?',
            'App\\Controller\\UserController::userList' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryCreate' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryEdit' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryDelete' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryList' => '?',
            'App\\Controller\\AbilityController:abilityCreate' => '?',
            'App\\Controller\\AbilityController:abilityEdit' => '?',
            'App\\Controller\\AbilityController:abilityDelete' => '?',
            'App\\Controller\\AbilityController:abilityList' => '?',
            'App\\Controller\\CardController:list' => '?',
            'App\\Controller\\CardController:cardCreate' => '?',
            'App\\Controller\\CardController:cardEdit' => '?',
            'App\\Controller\\CardController:cardDelete' => '?',
            'App\\Controller\\CardController:cardList' => '?',
            'App\\Controller\\SecurityController:signIn' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:userCreate' => '?',
            'App\\Controller\\UserController:userEdit' => '?',
            'App\\Controller\\UserController:userDelete' => '?',
            'App\\Controller\\UserController:userList' => '?',
        ]);
    }
}
