<?php

namespace ContainerGY5YgSY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbilityCategoryControllerabilityCategoryDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o_w.7CQ.App\Controller\AbilityCategoryController::abilityCategoryDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryDelete()'] = ($container->privates['.service_locator.o_w.7CQ'] ?? $container->load('get_ServiceLocator_OW_7CQService'))->withContext('App\\Controller\\AbilityCategoryController::abilityCategoryDelete()', $container);
    }
}
