<?php

namespace ContainerVUbAf0a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApplicationController' shared autowired service.
     *
     * @return \App\Controller\ApplicationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApplicationController.php';

        $container->services['App\\Controller\\ApplicationController'] = $instance = new \App\Controller\ApplicationController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ApplicationController', $container));

        return $instance;
    }
}
