<?php

namespace ContainerVUbAf0a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardDeckControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JfWF6yZ.App\Controller\CardDeckController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JfWF6yZ.App\\Controller\\CardDeckController::list()'] = ($container->privates['.service_locator.JfWF6yZ'] ?? $container->load('get_ServiceLocator_JfWF6yZService'))->withContext('App\\Controller\\CardDeckController::list()', $container);
    }
}
