<?php

namespace Container4q1j81Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdministrationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UasAP0g.App\Controller\AdministrationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UasAP0g.App\\Controller\\AdministrationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abilityRepository' => ['privates', 'App\\Repository\\AbilityRepository', 'getAbilityRepositoryService', true],
            'cardRepository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
        ], [
            'abilityRepository' => 'App\\Repository\\AbilityRepository',
            'cardRepository' => 'App\\Repository\\CardRepository',
        ]))->withContext('App\\Controller\\AdministrationController::index()', $container);
    }
}
