<?php

namespace Container4q1j81Z;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardAPIControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CardAPIController' shared autowired service.
     *
     * @return \App\Controller\Api\ApiCardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CardAPIController.php';

        $container->services['App\\Controller\\Api\\ApiCardController'] = $instance = new \App\Controller\Api\ApiCardController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\ApiCardController', $container));

        return $instance;
    }
}
