<?php

namespace Container4q1j81Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardDeckControllerexportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KvNRweA.App\Controller\CardDeckController::export()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KvNRweA.App\\Controller\\CardDeckController::export()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardDeck' => ['privates', '.errored..service_locator.KvNRweA.App\\Entity\\CardDeck', NULL, 'Cannot autowire service ".service_locator.KvNRweA": it needs an instance of "App\\Entity\\CardDeck" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cardDeck' => 'App\\Entity\\CardDeck',
        ]))->withContext('App\\Controller\\CardDeckController::export()', $container);
    }
}
