<?php

namespace ContainerWMnKlll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VaGu42rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VaGu42r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VaGu42r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abilityRepository' => ['privates', 'App\\Repository\\AbilityRepository', 'getAbilityRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'abilityRepository' => 'App\\Repository\\AbilityRepository',
            'entityManagerInterface' => '?',
        ]);
    }
}
