<?php

namespace ContainerGUhtHXh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControlleruserListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bQ78HV5.App\Controller\UserController::userList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bQ78HV5.App\\Controller\\UserController::userList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\UserController::userList()', $container);
    }
}
