<?php

namespace ContainerSvIpwTl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdministrationControlleruserDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6uK6gmq.App\Controller\AdministrationController::userDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6uK6gmq.App\\Controller\\AdministrationController::userDelete()'] = ($container->privates['.service_locator.6uK6gmq'] ?? $container->load('get_ServiceLocator_6uK6gmqService'))->withContext('App\\Controller\\AdministrationController::userDelete()', $container);
    }
}
