<?php

namespace ContainerSvIpwTl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdministrationControllerabilityCategoryListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bVsO2JX.App\Controller\AdministrationController::abilityCategoryList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bVsO2JX.App\\Controller\\AdministrationController::abilityCategoryList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abilityCategoryRepository' => ['privates', 'App\\Repository\\AbilityCategoryRepository', 'getAbilityCategoryRepositoryService', true],
        ], [
            'abilityCategoryRepository' => 'App\\Repository\\AbilityCategoryRepository',
        ]))->withContext('App\\Controller\\AdministrationController::abilityCategoryList()', $container);
    }
}
