<?php

namespace ContainerHC9DfAU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbilityControllerabilityDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VaGu42r.App\Controller\AbilityController::abilityDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityDelete()'] = ($container->privates['.service_locator.VaGu42r'] ?? $container->load('get_ServiceLocator_VaGu42rService'))->withContext('App\\Controller\\AbilityController::abilityDelete()', $container);
    }
}
