<?php

namespace ContainerHC9DfAU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllercardDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cz_FD95.App\Controller\CardController::cardDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cz_FD95.App\\Controller\\CardController::cardDelete()'] = ($container->privates['.service_locator.Cz_FD95'] ?? $container->load('get_ServiceLocator_CzFD95Service'))->withContext('App\\Controller\\CardController::cardDelete()', $container);
    }
}
