<?php

namespace ContainerHC9DfAU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControlleradministrationCardListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1_hm3sa.App\Controller\CardController::administrationCardList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1_hm3sa.App\\Controller\\CardController::administrationCardList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardRepository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'cardRepository' => 'App\\Repository\\CardRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\CardController::administrationCardList()', $container);
    }
}
