<?php

namespace Container8rRGxtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JfWF6yZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JfWF6yZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JfWF6yZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardDeckRepository' => ['privates', 'App\\Repository\\CardDeckRepository', 'getCardDeckRepositoryService', true],
            'cardRepository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cardDeckRepository' => 'App\\Repository\\CardDeckRepository',
            'cardRepository' => 'App\\Repository\\CardRepository',
            'entityManager' => '?',
        ]);
    }
}
