<?php

namespace Container8rRGxtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbilityControllerabilityCreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UmW841m.App\Controller\AbilityController::abilityCreate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UmW841m.App\\Controller\\AbilityController::abilityCreate()'] = ($container->privates['.service_locator.UmW841m'] ?? $container->load('get_ServiceLocator_UmW841mService'))->withContext('App\\Controller\\AbilityController::abilityCreate()', $container);
    }
}
