<?php

namespace Container6A3S1IS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardAPIControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9AEQ_R8.App\Controller\CardAPIController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9AEQ_R8.App\\Controller\\CardAPIController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\CardRepository', 'getCardRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'repository' => 'App\\Repository\\CardRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\CardAPIController::list()', $container);
    }
}
