<?php

namespace Container6A3S1IS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControlleradministrationUserDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d8rsN5P.App\Controller\UserController::administrationUserDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d8rsN5P.App\\Controller\\UserController::administrationUserDelete()'] = ($container->privates['.service_locator.d8rsN5P'] ?? $container->load('get_ServiceLocator_D8rsN5PService'))->withContext('App\\Controller\\UserController::administrationUserDelete()', $container);
    }
}
