<?php

namespace ContainerXFlviG4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCopyCardDeckFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CopyCardDeckForm' shared autowired service.
     *
     * @return \App\Form\CopyCardDeckForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CopyCardDeckForm.php';

        return $container->privates['App\\Form\\CopyCardDeckForm'] = new \App\Form\CopyCardDeckForm();
    }
}
