<?php

namespace Container6ixmif8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardAPIControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qWMrN3u.App\Controller\CardAPIController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qWMrN3u.App\\Controller\\CardAPIController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'card' => ['privates', '.errored..service_locator.qWMrN3u.App\\Entity\\Card', NULL, 'Cannot autowire service ".service_locator.qWMrN3u": it needs an instance of "App\\Entity\\Card" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'card' => 'App\\Entity\\Card',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\CardAPIController::show()', $container);
    }
}
