<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVUbAf0a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVUbAf0a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVUbAf0a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVUbAf0a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVUbAf0a\App_KernelDevDebugContainer([
    'container.build_hash' => 'VUbAf0a',
    'container.build_id' => '6631aa97',
    'container.build_time' => 1748597471,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVUbAf0a');
