<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvIpwTl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvIpwTl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSvIpwTl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSvIpwTl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSvIpwTl\App_KernelDevDebugContainer([
    'container.build_hash' => 'SvIpwTl',
    'container.build_id' => 'f18f9f0c',
    'container.build_time' => 1747605592,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSvIpwTl');
