<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZwCDt3X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZwCDt3X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZwCDt3X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZwCDt3X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZwCDt3X\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZwCDt3X',
    'container.build_id' => 'b7f67746',
    'container.build_time' => 1748399971,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZwCDt3X');
