<?php

namespace ContainerTIg4wwq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbilityCategoryControllerabilityCategoryListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.raa5GFv.App\Controller\AbilityCategoryController::abilityCategoryList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.raa5GFv.App\\Controller\\AbilityCategoryController::abilityCategoryList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abilityCategoryRepository' => ['privates', 'App\\Repository\\AbilityCategoryRepository', 'getAbilityCategoryRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'abilityCategoryRepository' => 'App\\Repository\\AbilityCategoryRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\AbilityCategoryController::abilityCategoryList()', $container);
    }
}
