<?php

namespace ContainerTIg4wwq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbilityControllerabilityListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cx3b8LV.App\Controller\AbilityController::abilityList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cx3b8LV.App\\Controller\\AbilityController::abilityList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abilityRepository' => ['privates', 'App\\Repository\\AbilityRepository', 'getAbilityRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'abilityRepository' => 'App\\Repository\\AbilityRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\AbilityController::abilityList()', $container);
    }
}
