<?php

namespace ContainerKtis6df;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4KK4v2fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4KK4v2f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4KK4v2f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryList' => ['privates', '.service_locator.raa5GFv.App\\Controller\\AbilityCategoryController::abilityCategoryList()', 'getAbilityCategoryControllerabilityCategoryListService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityCategoryController::abilityCategoryCreate()', 'getAbilityCategoryControllerabilityCategoryCreateService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryEdit' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryEdit()', 'getAbilityCategoryControllerabilityCategoryEditService', true],
            'App\\Controller\\AbilityCategoryController::abilityCategoryDelete' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryDelete()', 'getAbilityCategoryControllerabilityCategoryDeleteService', true],
            'App\\Controller\\AbilityController::abilityCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityController::abilityCreate()', 'getAbilityControllerabilityCreateService', true],
            'App\\Controller\\AbilityController::abilityEdit' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityEdit()', 'getAbilityControllerabilityEditService', true],
            'App\\Controller\\AbilityController::abilityDelete' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityDelete()', 'getAbilityControllerabilityDeleteService', true],
            'App\\Controller\\AbilityController::abilityList' => ['privates', '.service_locator.imJR4sZ.App\\Controller\\AbilityController::abilityList()', 'getAbilityControllerabilityListService', true],
            'App\\Controller\\AdministrationController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\AdministrationController::index()', 'getAdministrationControllerindexService', true],
            'App\\Controller\\CardController::list' => ['privates', '.service_locator.NMBx11d.App\\Controller\\CardController::list()', 'getCardControllerlistService', true],
            'App\\Controller\\CardController::administrationCardList' => ['privates', '.service_locator.1_hm3sa.App\\Controller\\CardController::administrationCardList()', 'getCardControlleradministrationCardListService', true],
            'App\\Controller\\CardController::cardCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\CardController::cardCreate()', 'getCardControllercardCreateService', true],
            'App\\Controller\\CardController::cardEdit' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardEdit()', 'getCardControllercardEditService', true],
            'App\\Controller\\CardController::cardDelete' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardDelete()', 'getCardControllercardDeleteService', true],
            'App\\Controller\\SecurityController::signIn' => ['privates', '.service_locator.UmW841m.App\\Controller\\SecurityController::signIn()', 'getSecurityControllersignInService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::administrationUserList' => ['privates', '.service_locator.bQ78HV5.App\\Controller\\UserController::administrationUserList()', 'getUserControlleradministrationUserListService', true],
            'App\\Controller\\UserController::administrationUserCreate' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserController::administrationUserCreate()', 'getUserControlleradministrationUserCreateService', true],
            'App\\Controller\\UserController::administrationUserEdit' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\UserController::administrationUserEdit()', 'getUserControlleradministrationUserEditService', true],
            'App\\Controller\\UserController::administrationUserDelete' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\UserController::administrationUserDelete()', 'getUserControlleradministrationUserDeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryList' => ['privates', '.service_locator.raa5GFv.App\\Controller\\AbilityCategoryController::abilityCategoryList()', 'getAbilityCategoryControllerabilityCategoryListService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityCategoryController::abilityCategoryCreate()', 'getAbilityCategoryControllerabilityCategoryCreateService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryEdit' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryEdit()', 'getAbilityCategoryControllerabilityCategoryEditService', true],
            'App\\Controller\\AbilityCategoryController:abilityCategoryDelete' => ['privates', '.service_locator.o_w.7CQ.App\\Controller\\AbilityCategoryController::abilityCategoryDelete()', 'getAbilityCategoryControllerabilityCategoryDeleteService', true],
            'App\\Controller\\AbilityController:abilityCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\AbilityController::abilityCreate()', 'getAbilityControllerabilityCreateService', true],
            'App\\Controller\\AbilityController:abilityEdit' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityEdit()', 'getAbilityControllerabilityEditService', true],
            'App\\Controller\\AbilityController:abilityDelete' => ['privates', '.service_locator.VaGu42r.App\\Controller\\AbilityController::abilityDelete()', 'getAbilityControllerabilityDeleteService', true],
            'App\\Controller\\AbilityController:abilityList' => ['privates', '.service_locator.imJR4sZ.App\\Controller\\AbilityController::abilityList()', 'getAbilityControllerabilityListService', true],
            'App\\Controller\\AdministrationController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\AdministrationController::index()', 'getAdministrationControllerindexService', true],
            'App\\Controller\\CardController:list' => ['privates', '.service_locator.NMBx11d.App\\Controller\\CardController::list()', 'getCardControllerlistService', true],
            'App\\Controller\\CardController:administrationCardList' => ['privates', '.service_locator.1_hm3sa.App\\Controller\\CardController::administrationCardList()', 'getCardControlleradministrationCardListService', true],
            'App\\Controller\\CardController:cardCreate' => ['privates', '.service_locator.UmW841m.App\\Controller\\CardController::cardCreate()', 'getCardControllercardCreateService', true],
            'App\\Controller\\CardController:cardEdit' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardEdit()', 'getCardControllercardEditService', true],
            'App\\Controller\\CardController:cardDelete' => ['privates', '.service_locator.Cz_FD95.App\\Controller\\CardController::cardDelete()', 'getCardControllercardDeleteService', true],
            'App\\Controller\\SecurityController:signIn' => ['privates', '.service_locator.UmW841m.App\\Controller\\SecurityController::signIn()', 'getSecurityControllersignInService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:administrationUserList' => ['privates', '.service_locator.bQ78HV5.App\\Controller\\UserController::administrationUserList()', 'getUserControlleradministrationUserListService', true],
            'App\\Controller\\UserController:administrationUserCreate' => ['privates', '.service_locator.egipcEH.App\\Controller\\UserController::administrationUserCreate()', 'getUserControlleradministrationUserCreateService', true],
            'App\\Controller\\UserController:administrationUserEdit' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\UserController::administrationUserEdit()', 'getUserControlleradministrationUserEditService', true],
            'App\\Controller\\UserController:administrationUserDelete' => ['privates', '.service_locator.d8rsN5P.App\\Controller\\UserController::administrationUserDelete()', 'getUserControlleradministrationUserDeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryList' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryCreate' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryEdit' => '?',
            'App\\Controller\\AbilityCategoryController::abilityCategoryDelete' => '?',
            'App\\Controller\\AbilityController::abilityCreate' => '?',
            'App\\Controller\\AbilityController::abilityEdit' => '?',
            'App\\Controller\\AbilityController::abilityDelete' => '?',
            'App\\Controller\\AbilityController::abilityList' => '?',
            'App\\Controller\\AdministrationController::index' => '?',
            'App\\Controller\\CardController::list' => '?',
            'App\\Controller\\CardController::administrationCardList' => '?',
            'App\\Controller\\CardController::cardCreate' => '?',
            'App\\Controller\\CardController::cardEdit' => '?',
            'App\\Controller\\CardController::cardDelete' => '?',
            'App\\Controller\\SecurityController::signIn' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::administrationUserList' => '?',
            'App\\Controller\\UserController::administrationUserCreate' => '?',
            'App\\Controller\\UserController::administrationUserEdit' => '?',
            'App\\Controller\\UserController::administrationUserDelete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryList' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryCreate' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryEdit' => '?',
            'App\\Controller\\AbilityCategoryController:abilityCategoryDelete' => '?',
            'App\\Controller\\AbilityController:abilityCreate' => '?',
            'App\\Controller\\AbilityController:abilityEdit' => '?',
            'App\\Controller\\AbilityController:abilityDelete' => '?',
            'App\\Controller\\AbilityController:abilityList' => '?',
            'App\\Controller\\AdministrationController:index' => '?',
            'App\\Controller\\CardController:list' => '?',
            'App\\Controller\\CardController:administrationCardList' => '?',
            'App\\Controller\\CardController:cardCreate' => '?',
            'App\\Controller\\CardController:cardEdit' => '?',
            'App\\Controller\\CardController:cardDelete' => '?',
            'App\\Controller\\SecurityController:signIn' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:administrationUserList' => '?',
            'App\\Controller\\UserController:administrationUserCreate' => '?',
            'App\\Controller\\UserController:administrationUserEdit' => '?',
            'App\\Controller\\UserController:administrationUserDelete' => '?',
        ]);
    }
}
